<ul class="nav nav-pills nav-stacked">
  <li><a href="<?php echo URL; ?>dashboard">Home</a></li>
  <li><a href="<?php echo URL; ?>profile">Profile</a></li>
  <li><a href="<?php echo URL; ?>calendar">Calendar</a></li>
  <li><a href="<?php echo URL; ?>browsegrants">Browse Grants</a></li>
  <li><a href="<?php echo URL; ?>reviewgrants">Review Grants</a></li>
  <li><a href="<?php echo URL; ?>logout">Logout</a></li>
</ul>